### ISSUE TITLE
log file for BaitFilter-v1.0.5

### ISSUE THREAD

**Issue by alexdonath** [cmayer/BaitFisher-package#2]
If many different post-analyses are performed with BaitFilter one could loose track which settings were used in each analysis. It would be good to either print a log file with the applied parameters or to provide them to BaitFilter via a parameter file (similar to BaitFisher).

**Comment by cmayer** [comment]
Dear Alex, thanks for this suggestion. I included this in the next version.
Christoph

**Comment by cmayer** [comment]
The log file now contains the full command with which BaitFilter was called.
