### ISSUE TITLE
--version flag of BaitFilter-v1.0.5

### ISSUE THREAD

**Issue by alexdonath** [cmayer/BaitFisher-package#3]
Isn't the --version flag of BaitFilter-v1.0.5 kind of unnecessary because it already has the version string in its name?

**Comment by cmayer** [comment]
Dear Alex,
thanks for your suggestion. I considered your suggestion but decided to leave it as it is for two reasons:
a) --version flag is a standard flag in many programs.
b) the user might have renamed the executable and wants to check which version it was that he used. It has happend to me before.

Thanks again. An updated version which fixes a few other small issues will be made available soon.
Best Christoph
